un: |
          pytest
  # codecoverage:
  #   runs-on: ubuntu-latest # choose the OS for running the action
  #   strategy:
  #     matrix: 
  #       python: ['3.7', '3.8', '3.9']
  #   env:
  #     PYTHON: ${{ matrix.python }}
  #   # define the individual sequential steps to be run
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v2
  #     - name: Setup python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python }}
  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt
  #     - name: Generate coverage report
  #       run: |
  #         pip install pytest-cov
  #         pytest --cov=./ --cov-report=xml
  #         cat coverage.xml
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v2
  #       with:
  #         # env_vars: PYTHON
  #         fail_ci_if_error: true
  #         verbose: true
